import 'package:flutter/material.dart';

import 'package:font_awesome_flutter/font_awesome_flutter.dart';

IconData getIcon(String category) {
  switch (category) {
    case "splash":
      return Icons.wallet_rounded;
    case "add":
      return Icons.add;
    case "language":
      return Icons.language;
    case "settings":
      return Icons.settings;
    case "logOut":
      return Icons.logout;
    case "signIn":
      return Icons.login;
    case "calendar":
      return Icons.calendar_month;
    case "home":
      return Icons.home_rounded;
    case "arrowDropDown":
      return Icons.arrow_drop_down;
    case "check":
      return Icons.check;
    case "clear":
      return Icons.clear;
    case "error":
      return Icons.error_outline;
    case "info":
      return Icons.info_outline;
    case "warning":
      return Icons.warning_amber_rounded;
    case "success":
      return Icons.check_circle_outlined;
    case "viewText":
      return Icons.remove_red_eye;
    case "obscureText":
      return Icons.visibility_off;
    case "history":
      return Icons.history;
    case "expenses":
      return FontAwesomeIcons.moneyBill;
    case "profits":
      return FontAwesomeIcons.piggyBank;
    case "currency":
      return FontAwesomeIcons.dollarSign;
    case "bank":
      return Icons.assured_workload;
    case "previousPage":
      return Icons.arrow_back_ios_rounded;
    case "nextPage":
      return Icons.arrow_forward_ios_rounded;
    case "food":
      return Icons.fastfood_rounded;
    case "games":
      return FontAwesomeIcons.gamepad;
    case "entertainment":
      return FontAwesomeIcons.ticket;
    case "gas":
      return Icons.local_gas_station_rounded;
    case "parking":
      return Icons.local_parking;
    case "shopping":
      return Icons.shopping_cart;
    case "electronic":
      return Icons.electrical_services_rounded;
    case "accessories":
      return Icons.diamond;
    case "present":
      return Icons.wallet_giftcard_rounded;
    case "service":
      return Icons.room_service;
    case "loan":
      return FontAwesomeIcons.coins;
    case "payment":
      return FontAwesomeIcons.moneyBills;
    case "pay":
      return Icons.payment;
    case "car":
      return FontAwesomeIcons.car;
    case "cleaning":
      return Icons.cleaning_services_rounded;
    case "sale":
      return Icons.point_of_sale;
    case "change":
      return FontAwesomeIcons.moneyBillTransfer;
    case "commission":
      return FontAwesomeIcons.userMinus;
    case "homeCategory":
      return FontAwesomeIcons.house;
    case "<":
      return FontAwesomeIcons.deleteLeft;
    case "0":
      return FontAwesomeIcons.zero;
    case "1":
      return FontAwesomeIcons.one;
    case "2":
      return FontAwesomeIcons.two;
    case "3":
      return FontAwesomeIcons.three;
    case "4":
      return FontAwesomeIcons.four;
    case "5":
      return FontAwesomeIcons.five;
    case "6":
      return FontAwesomeIcons.six;
    case "7":
      return FontAwesomeIcons.seven;
    case "8":
      return FontAwesomeIcons.eight;
    case "9":
      return FontAwesomeIcons.nine;
    case "A":
      return FontAwesomeIcons.a;
    case "C":
      return FontAwesomeIcons.c;
    case 'pencil':
      return FontAwesomeIcons.pencil;
    case 'bin':
      return Icons.delete_forever;
    case 'menu':
      return Icons.menu_rounded;
    case 'back':
      return Icons.arrow_back_ios_new;
    default:
      return Icons.question_mark;
  }
}
