import 'package:flutter/material.dart';

IconData getIcon(String category) {
  switch (category) {
    case "splash":
      return Icons.wallet_rounded;
    case "add":
      return Icons.add;
    case "language":
      return Icons.language;
    case "settings":
      return Icons.settings;
    case "logOut":
      return Icons.logout;
    case "signIn":
      return Icons.login;
    case "calendar":
      return Icons.calendar_month;
    case "home":
      return Icons.home_rounded;
    case "arrowDropDown":
      return Icons.arrow_drop_down;
    case "check":
      return Icons.check;
    case "clear":
      return Icons.clear;
    case "error":
      return Icons.error_outline;
    case "info":
      return Icons.info_outline;
    case "warning":
      return Icons.warning_amber_rounded;
    case "success":
      return Icons.check_circle_outlined;
    case "viewText":
      return Icons.remove_red_eye;
    case "obscureText":
      return Icons.visibility_off;
    case "history":
      return Icons.history;
    case "currency":
      return Icons.currency_exchange;
    case "bank":
      return Icons.assured_workload;
    case "previousPage":
      return Icons.arrow_back_ios_rounded;
    case "nextPage":
      return Icons.arrow_forward_ios_rounded;
    case "food":
      return Icons.fastfood_rounded;
    case "games":
      return Icons.gamepad_rounded;
    case "entertainment":
      return Icons.local_attraction;
    case "gas":
      return Icons.local_gas_station_rounded;
    case "parking":
      return Icons.local_parking;
    case "shopping":
      return Icons.shopping_cart;
    case "electronic":
      return Icons.electrical_services_rounded;
    case "accessories":
      return Icons.diamond;
    case "present":
      return Icons.wallet_giftcard_rounded;
    case "service":
      return Icons.room_service;
    case "loan":
      return Icons.handshake;
    case "payment":
      return Icons.payment_rounded;
    case "pay":
      return Icons.payments;
    case "car":
      return Icons.car_rental;
    case "cleaning":
      return Icons.cleaning_services_rounded;
    case "sale":
      return Icons.point_of_sale;
    case "change":
      return Icons.change_circle;
    case "commission":
      return Icons.playlist_remove_outlined;
    default:
      return Icons.question_mark;
  }
}
